### PR TITLE
Support new clipboard type : Theme

### PR DESCRIPTION
**Pull request by matsuo**
I'd like to say a big thank you for your software.
I wrote a patch which supports handling themes. This is a quick hack. Please check it out.

### CODE REVIEW

**Comment by harawata** [comment]
Hi @matsuo ,

Thank you for the PR!
I thought that my boss was the only user. XD

Looking at the change, I'll probably drop OSType and use UTI directly from now on.
Please let me know if you think that's a bad idea.

**Comment by matsuo** [comment]
Thanks you for your response!
Using UTI directly is a good idea. Please change so.

**Comment by matsuo** [comment]
FYI:
// dyn.ah62d4rv4gk8zuxnykk: Table
// dyn.ah62d4rv4gk8zuxngku: Field
// dyn.ah62d4rv4gk8zuxnxkq: Script
// dyn.ah62d4rv4gk8zuxnxnq: Script Step
// dyn.ah62d4rv4gk8zuxngm2: Custom Function
// dyn.ah62d4rv4gk8zuxnqm6: Layout Object (.fp7)
// dyn.ah62d4rv4gk8zuxnqgk: Layout Object (.fmp12)
// dyn.ah62d4rv4gk8zuxn0mu: Value List
// dyn.agk8u              : Theme
// public.utf16-plain-text: Custom Menu

**Comment by harawata** [comment]
Thanks for the info, @matsuo !
Released version 2.2. Please let me know if there is any problem.
https://github.com/harawata/fmclipboardbroker/releases/tag/2.2

Regarding custom menu, I think it's better not to support 'public.utf16-plain-text' as it's a pretty common type.
And, as you may be aware, this type can be copied/pasted directly between FM and text editors.

**Comment by matsuo** [comment]
I think it's better not to support 'public.utf16-plain-text, too.

By the way, after launching FMClipboardBroker 2.2, macOS (Mojave) shows an error message '“FMClipboardBroker.app” is damaged and can’t be opened'.

I think FMClipboardBroker.app in "fmclipboardbroker-2.2.dmg" doesn't reflect latest codes, date modified of FMClipboardBroker.app in "fmclipboardbroker-2.2.dmg" is Jan 12 2019, 18:21.

**Comment by harawata** [comment]
The build worked fine on 10.14.2 for me, but I've cleaned and rebuilt the .app and replaced the .dmg on the release page.
Could you try the new .dmg (created on 2019-01-13T03:54) please?
Sorry for the inconvenience!

**Comment by matsuo** [comment]
The new .dmg (created on 2019-01-13T03:54) works for me.
Thanks a lot!

**Comment by harawata** [comment]
Good! Thanks again for your help!

**Pull request merged**
