### PR TITLE
Add support for Claris FileMaker 2024

### PR DESCRIPTION
**Pull request by matsuo**
Hi,

This PR adds support for Claris FileMaker 2024 to be able to handle themes.
Please check it out if you have time.

FYI:
UTI of themes in FileMaker 2023: dyn.agk8u
UTI of themes in FileMaker 2024: dyn.ah62d4rv4gk8zuxnyma

### CODE REVIEW

**Comment by harawata** [comment]
Thank you for the PR, @matsuo ,

Having list items with the same label (Theme) may be confusing.
How about "Theme (v2024+)" for the new one?

image

At this point, I am 98.94% certain that you are the only user 😆
So, whatever works for you is fine by me.

**Comment by matsuo** [comment]
Thank you for your comment!
I think developers and users who use Claris FileMaker are just shy :)

I see,  I think "Theme (v2024+)" is better, too.
And I am thinking of changing the PR so that “Theme” appears above “Theme (v2024+)”.

After receiving your comment and thinking about it, I think we should need a "Read theme in v2024 format" option.
I'll give it some more thought this coming weekend.

**Comment by matsuo** [comment]
@harawata
After some thought, I have updated this PR and have added "Read theme in v2024 format" option.
And I have adjusted to detect Script Folders for scripts (XMSC) type in 01e3f5fbca07b33e85ef0c8079aca9022274b32f commit.

How do you think?

**Comment by harawata** [comment]
Thank you for the update, @matsuo !

[2.3](https://github.com/harawata/fmclipboardbroker/releases/tag/2.3) is released.
I don't have an environment to test the new v2024 theme type, so please let me know if there is any problem.

**Comment by matsuo** [comment]
@harawata 
Version 2.3 works for me! Thank you so much!

I have confirmed the following behavior to be as expected below.

- If enabled "Read themes in v2024 format" and clicked the "Load" button:
  - Can paste the theme when using FileMaker 2024.
  - Can't paste the theme when using FileMaker 2023 or previous.
- If disabled "Read themes in v2024 format" and clicked the "Load" button:
  - Can't paste the theme when using FileMaker 2024.
  - Can paste the theme when using FileMaker 2023 or previous.

The content of the file saved as an XML file from FileMaker Pro 2024 and the content of the file saved as an XML file from FileMaker Pro 2023 is exactly the same, so I had added the "Read themes in v2024 format" option.

Thank you.

**Pull request merged**
